name = "xai-finance"
type = "webpack"
account_id = ""  # 部署时需要填写实际的Cloudflare账户ID
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-09-01"

[site]
bucket = "../.next/static"  # 指向构建后的静态资源
entry-point = "workers-site"

[env.production]
workers_dev = false

# 环境变量配置
[vars]
NEXT_PUBLIC_APP_URL = ""   # 部署后需要设置实际的URL
AVE_API_KEY = ""  # 需要设置实际的API密钥

# KV命名空间配置
[[kv_namespaces]]
binding = "ASSETS"
id = ""  # 部署时需要填写KV命名空间ID 